### PR TITLE
EmberObjectQueryManager for ember class and services

### PR DESCRIPTION
**Pull request by villander**
`EmberObjectQueryManager` is necessary for [services](https://emberjs.com/api/ember/2.15/classes/Ember.Service/methods/willDestroy?anchor=willDestroy) (for example a chat service with data loading) and [class](https://github.com/poteto/ember-metrics/blob/master/addon/metrics-adapters/base.js#L19) that extend `Ember.Object`

### CODE REVIEW

**Comment by bgentry** [comment]
@villander looks great! I think my only question is whether this mixin should be named `EmberObjectQueryManager` or the shorter `ObjectQueryManager`. I'm leaning towards the shorter one to better line up with the other 2.

Do you agree and can you make those changes if so? Thanks :v:

**Comment by villander** [comment]
Done @bgentry

**Comment by bgentry** [comment]
Thanks @villander! :clap: :boom:

I can't cut a release right now but will do so this week

**Comment by villander** [comment]
No problem 🇧🇷

**Pull request merged**
