### PR TITLE
Switch to extracted graphql filter as npm dep

### PR DESCRIPTION
**Pull request by csantero**
I don't currently use ember-apollo-client in my project, but I need the same broccoli functionality for .graphql files. I extracted the graphql filter into a separate npm package, so that improvements like the switch to broccoli-persistent-filter could be more easily shared.

### CODE REVIEW

**Comment by bgentry** [comment]
Nice!

I'm ok with this provided that you add an MIT license to [broccoli-graphql-filter](https://github.com/csantero/broccoli-graphql-filter) and maintain the credit to @dfreeman and myself in the readme.

How about you, @dfreeman ?

**Comment by dfreeman** [comment]
Fine by me!

**Comment by csantero** [comment]
@bgentry I've added an MIT LICENSE.md to broccoli-graphql-filter, and updated the PR to point to a new version that includes the license.

**Comment by bgentry** [comment]
Thanks @csantero :v:

**Pull request merged**
